### ISSUE TITLE
PySerial having problems with Arduino Yun

### ISSUE THREAD

**Issue by mseroczynski** [pyserial/pyserial#19]
Hello, I've already had some discussion on this issue on PlatformIO Github - please look at trace log below:
(https://github.com/platformio/platformio/issues/294#issuecomment-145293081)

``python -m serial.tools.list_ports -v`` returns:
``Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/private/tmp/piotest/lib/python2.7/site-packages/serial/tools/list_ports.py", line 102, in <module> main() File "/private/tmp/piotest/lib/python2.7/site-packages/serial/tools/list_ports.py", line 84, in main iterator = sorted(comports()) File "/private/tmp/piotest/lib/python2.7/site-packages/serial/tools/list_ports_osx.py", line 233, in comports serial_interfaces = scan_interfaces() File "/private/tmp/piotest/lib/python2.7/site-packages/serial/tools/list_ports_osx.py", line 209, in scan_interfaces device = get_string_property(service, "IOCalloutDevice") File "/private/tmp/piotest/lib/python2.7/site-packages/serial/tools/list_ports_osx.py", line 101, in get_string_property output = cf.CFStringGetCStringPtr(CFContainer, 0).decode('mac_roman') AttributeError: 'NoneType' object has no attribute 'decode'``

**Comment by zsquareplusc** [comment]
can you try again with the latest version from git? I pushed a change that should fix this.

**Comment by mseroczynski** [comment]
Ok, with 3.0a1 it's like below:

```
(piotest)MacBook-Pro-ches:tmp ches$ pip list
pip (7.1.2)
pyserial (3.0a1)
setuptools (18.2)
wheel (0.24.0)
(piotest)MacBook-Pro-ches:tmp ches$ python -m serial.tools.list_ports -v
no ports found
(piotest)MacBook-Pro-ches:tmp ches$ ls /dev/cu*
/dev/cu.Bluetooth-Incoming-Port	/dev/cu.usbmodem1421
(piotest)MacBook-Pro-ches:tmp ches$ 
```

**Comment by mseroczynski** [comment]
Ok, with 3.0a1 it's like below:

```
(piotest)MacBook-Pro-ches:tmp ches$ pip list
pip (7.1.2)
pyserial (3.0a1)
setuptools (18.2)
wheel (0.24.0)
(piotest)MacBook-Pro-ches:tmp ches$ python -m serial.tools.list_ports -v
no ports found
(piotest)MacBook-Pro-ches:tmp ches$ ls /dev/cu*
/dev/cu.Bluetooth-Incoming-Port	/dev/cu.usbmodem1421
(piotest)MacBook-Pro-ches:tmp ches$ 
```

**Comment by hoihu** [comment]
What's the output of:
`ioreg -c IOSerialBSDClient | grep IOCalloutDevice`

**Comment by d235j** [comment]
Works with Python 2.7, does not work with 3.5. Weird.

**Comment by mseroczynski** [comment]
```
    | | | |   |   |     |           "IOCalloutDevice" = "/dev/cu.usbmodem14141"
      |           "IOCalloutDevice" = "/dev/cu.Bluetooth-Incoming-Port"
```

**Comment by mseroczynski** [comment]
@hoihu Any good news for me?

**Comment by hoihu** [comment]
It seems that your Macbook has the proper registry entries. 

But it doesn't list any of the callout devices (it should for example also list your cu.Bluetooth-Incoming-Port) - so it's not an issue with your board. On my Imac the cu.Bluetooth-Incoming-Port is listed correctly.

comport() iterates through the registry as apple proposes by using the IOSerialBDSClient service and then through the available IOCalloutDevices (which are mapped as cu.xxxx devices under /dev)

Maybe the Ctypes interface is not working as expected (specifically GetIOServicesByType). I'm running my test under OSX 10.10.3, which version are you using?   

There are no additional debug versions available, but you could patch comport() in list_ports_osx.py by adding:
```python
    for service in services:
        print service
```
this will just print one number per service that was found, but then you have at least a clue that the service has been recognised by the GetIOServicesByType call. If no numbers are showing up then the fault is in the GetIOServicesByType function.

If I find some time I'll do some tests on a Macbook.

**Comment by hoihu** [comment]
@mseroczynski: Based on your reference, your issue is resolved? Can this be closed then?

**Comment by mseroczynski** [comment]
Yup, my issue was resolved, thank you!

**Comment by hoihu** [comment]
so please close it then...
